version: '3'

services:
  nginx-proxy:
    image: jwilder/nginx-proxy
    restart: always
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./proxy-settings.conf:/etc/nginx/conf.d/proxy-settings.conf

networks:
  default:
    external:
      name: nginx-proxy
